// generated by cultio/switch/generate.py
// Architecture: AMD64
// Platform: Unix

void sswitch(void **ostack, void **dstack) {
    __asm__ __volatile__ (
        "sub rsp, 48\n"
        "mov QWORD PTR [rsp+0x0], r12\n"
        "mov QWORD PTR [rsp+0x8], r13\n"
        "mov QWORD PTR [rsp+0x10], r14\n"
        "mov QWORD PTR [rsp+0x18], r15\n"
        "mov QWORD PTR [rsp+0x20], rbx\n"
        "mov QWORD PTR [rsp+0x28], rbp\n"

        "mov QWORD PTR [rdi], rsp\n"
        "mov rsp, QWORD PTR [rsi]\n"

        "mov r12, QWORD PTR [rsp+0x0]\n"
        "mov r13, QWORD PTR [rsp+0x8]\n"
        "mov r14, QWORD PTR [rsp+0x10]\n"
        "mov r15, QWORD PTR [rsp+0x18]\n"
        "mov rbx, QWORD PTR [rsp+0x20]\n"
        "mov rbp, QWORD PTR [rsp+0x28]\n"
        "add rsp, 48\n"

        "pop rcx\n"
        "jmp rcx\n"
    );
}
