// generated by cultio/switch/generate.py
// Architecture: AMD64
// Platform: Unix

void sswitch(void **ostack, void **dstack) {
    __asm__ __volatile__ (
        "subq $0x30, %rsp\n"
        "movq %r12, 0x0(%rsp)\n"
        "movq %r13, 0x8(%rsp)\n"
        "movq %r14, 0x10(%rsp)\n"
        "movq %r15, 0x18(%rsp)\n"
        "movq %rbx, 0x20(%rsp)\n"
        "movq %rbp, 0x28(%rsp)\n"

        "movq %rsp, (%rdi)\n"
        "movq (%rsi), %rsp\n"

        "movq 0x0(%rsp), %r12\n"
        "movq 0x8(%rsp), %r13\n"
        "movq 0x10(%rsp), %r14\n"
        "movq 0x18(%rsp), %r15\n"
        "movq 0x20(%rsp), %rbx\n"
        "movq 0x28(%rsp), %rbp\n"
        "addq $0x30, %rsp\n"

        "popq %rcx\n"
        "jmpq %rcx\n"
    );
}
