; generated by cultio/switch/generate.py
; Architecture: AMD64
; Platform: Windows

BITS 64

global switch
section .text

sswitch:
    sub rsp, 0xa8
    movaps [rsp+0x0], xmm6
    movaps [rsp+0x10], xmm7
    movaps [rsp+0x20], xmm8
    movaps [rsp+0x30], xmm9
    movaps [rsp+0x40], xmm10
    movaps [rsp+0x50], xmm11
    movaps [rsp+0x60], xmm12
    movaps [rsp+0x70], xmm13
    movaps [rsp+0x80], xmm14
    movaps [rsp+0x90], xmm15
    push rsi
    push rdi
    push rbp
    push rbx
    push r12
    push r13
    push r14
    push r15
    push QWORD [gs:0x00]
    push QWORD [gs:0x08]
    push QWORD [gs:0x10]

    mov [rcx], rsp
    mov rsp, [rdx]

    pop rsi
    pop rdi
    pop rbp
    pop rbx
    pop r12
    pop r13
    pop r14
    pop r15
    pop QWORD [gs:0x00]
    pop QWORD [gs:0x08]
    pop QWORD [gs:0x10]
    movaps xmm6, [rsp+0x0]
    movaps xmm7, [rsp+0x10]
    movaps xmm8, [rsp+0x20]
    movaps xmm9, [rsp+0x30]
    movaps xmm10, [rsp+0x40]
    movaps xmm11, [rsp+0x50]
    movaps xmm12, [rsp+0x60]
    movaps xmm13, [rsp+0x70]
    movaps xmm14, [rsp+0x80]
    movaps xmm15, [rsp+0x90]

    mov rcx, [rsp+0xa8]
    add rsp, 0xa8
    jmp rcx
