; generated by cultio/switch/generate.py
; Architecture: AMD64
; Platform: Windows

BITS 64

global switch
section .text

sswitch:
    sub rsp, 232
    movaps [rsp+0x0], xmm6
    movaps [rsp+0x10], xmm7
    movaps [rsp+0x20], xmm8
    movaps [rsp+0x30], xmm9
    movaps [rsp+0x40], xmm10
    movaps [rsp+0x50], xmm11
    movaps [rsp+0x60], xmm12
    movaps [rsp+0x70], xmm13
    movaps [rsp+0x80], xmm14
    movaps [rsp+0x90], xmm15
    mov [rsp+0xa0], rsi
    mov [rsp+0xa8], rdi
    mov [rsp+0xb0], rbp
    mov [rsp+0xb8], rbx
    mov [rsp+0xc0], r12
    mov [rsp+0xc8], r13
    mov [rsp+0xd0], r14
    mov [rsp+0xd8], r15

    mov [rcx], rsp
    mov rsp, [rdx]

    movaps xmm6, [rsp+0x0]
    movaps xmm7, [rsp+0x10]
    movaps xmm8, [rsp+0x20]
    movaps xmm9, [rsp+0x30]
    movaps xmm10, [rsp+0x40]
    movaps xmm11, [rsp+0x50]
    movaps xmm12, [rsp+0x60]
    movaps xmm13, [rsp+0x70]
    movaps xmm14, [rsp+0x80]
    movaps xmm15, [rsp+0x90]
    mov rsi, [rsp+0xa0]
    mov rdi, [rsp+0xa8]
    mov rbp, [rsp+0xb0]
    mov rbx, [rsp+0xb8]
    mov r12, [rsp+0xc0]
    mov r13, [rsp+0xc8]
    mov r14, [rsp+0xd0]
    mov r15, [rsp+0xd8]
    add rsp, 232

    pop rcx
    jmp rcx
